name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  check-outdated-dependencies:
    name: Check Outdated Dependencies
    uses: valkyrjaio/.github/.github/workflows/_check-outdated-php-dependencies.yml@2b626b4cd5090fb9d998ba35450775bfea79b21b
    secrets: inherit
    with:
      php-version: '8.4'
      dependencies: |
        [
          {"name": "Root Packages", "command": "root-outdated-check-major-release"},
          {"name": "Rector", "command": "rector-outdated-check-major-release"}
        ]

  get-version:
    needs: check-outdated-dependencies
    uses: valkyrjaio/.github/.github/workflows/_get-version.yml@2b626b4cd5090fb9d998ba35450775bfea79b21b
    secrets: inherit

  create:
    needs: get-version
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@2b626b4cd5090fb9d998ba35450775bfea79b21b
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ needs.get-version.outputs.branch }}
