name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_update-php-dependencies.yml@a377bb5bc151aa160a65143b688f383fd085455f
    secrets: inherit
    with:
      php-version: '8.4'
      dependencies: |
        [
          {"name": "Root Packages",  "command": "update",                  "directory": "."},
          {"name": "Rector",         "command": "rector-composer-update",   "directory": ".github/ci/rector"}
        ]
